stages:
  - test

services:
  - postgres:latest

rspec:
  stage: test
  image: g3dinua/node-ruby:2.3.3
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - apt-get update -y && apt-get install -y locales mysql-client
    - echo "en_US UTF-8" > /etc/locale.gen
    - locale-gen en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - export LC_ALL=en_US.UTF-8
    - mkdir -p /cache/bin
    - ruby -v
    - gem install bundler
    - 'bundle_path=$(which bundle)'
    - bundle install --jobs $(nproc) --path=/cache/bundler
    - bundle exec rspec
  tags:
    - ruby

codeclimate:
  script:
    - docker info
    - 'docker run --interactive --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate engines:install'
    - 'docker run --interactive --rm --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json > codeclimate.json'
  stage: test
  tags:
    - codeclimate
  artifacts:
    paths: [codeclimate.json]
